language: cpp
sudo: false
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libcppunit-dev 
      - zlib1g-dev
script: cmake -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON . && make && make check

